config/routes.rb
Rails.application.routes.draw do
  get "homes", to: "homes#index"
  get "homes/company_profile", to: "homes#company_profile", as: "company_profile"

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: { estimate: 1, question: 2, introduction: 3 }

  validates :name, presence: true, length: { maximum: 20 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 30 },
                    format: { with: VALID_EMAIL_REGEX }

  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  validates :phone_number, presence: true, format: { with: VALID_PHONE_NUMBER_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  # 確認画面
  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end

  # 入力内容に誤りがあった場合
  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end

  def done

  end

  private

  def contact_params
    params.require(:contact)
          .permit(:email,
                  :name,
                  :phone_number,
                  :subject,
                  :message
                 )
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def company_profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/contacts/confirm.html.erb
</br>
<h2>入力内容確認</h2>
<nav aria-label="パンくずリスト" class="small">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'トップページ', homes_path %></li>
    <li class="breadcrumb-item active" aria-current="page">お問い合わせ</li>
  </ol>
</nav>
<hr />
<p>この内容で送信します。よろしいですか？</p>
<table>
  <tbody>
    <tr>
      <td class="text-center" style="width: 30%;">お名前</td>
      <td><%= @contact.name %></td>
    </tr>
    <tr>
      <td class="text-center" style="width: 30%;">email</td>
      <td><%= @contact.email %></td>
    </tr>
    <tr>
      <td class="text-center" style="width: 30%;">電話番号</td>
      <td><%= @contact.phone_number %></td>
    </tr>
    <tr>
      <td class="text-center" style="width: 30%;">件名</td>
      <td><%= @contact.subject %></td>
    </tr>
    <tr>
      <td class="text-center">メッセージ</td>
      <td style="white-space: pre-wrap;"><%= @contact.message %></td>
    </tr>
  </tbody>
  <tr>
    <td class="text-center" style="width: 30%;">
    <br>
      <%= form_for(@contact) do |f| %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :email %>
        <%= f.hidden_field :phone_number %>
        <%= f.hidden_field :subject %>
        <%= f.hidden_field :message %>
        <div><%= f.submit '送信', class: "btn btn-primary" %></div>
      <% end %>
    </td>
    <td>
    <br>
      <%= form_for @contact, url: back_path do |f| %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :email %>
        <%= f.hidden_field :phone_number %>
        <%= f.hidden_field :subject %>
        <%= f.hidden_field :message %>
        <div><%= f.submit '入力画面に戻る', class: "btn btn-danger" %></div>
      <% end %>
    </td>
  </tr>
</table>
<br>

app/views/contacts/done.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-12 col-lg-6 offset-lg-3">
      <h2>お問い合わせ完了</h2>
      <nav aria-label="パンくずリスト" class="small">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to 'トップページ', homes_path %></li>
          <li class="breadcrumb-item active" aria-current="page">お問い合わせ</li>
        </ol>
      </nav>
      <hr/>
      <p>ありがとうございます。お問い合わせ内容を送信しました。</p>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
</br>
<h2>お問合せフォーム</h2>
<nav aria-label="パンくずリスト" class="small">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'トップページ', homes_path %></li>
    <li class="breadcrumb-item active" aria-current="page">お問い合わせ</li>
  </ol>
</nav>
<hr />

<%= form_for(@contact, url: confirm_path) do |f| %>
  <% if @contact.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h5><strong>入力内容にエラーがあります。</strong></h5>
      <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" style="width: 30%;">
    <%= f.label :name, '*name*' %>
    <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "name", required: true %>
  </div>
  </br>
  <div class="form-group" style="width: 30%;">
    <%= f.label :name, '*Enter email*'%>
    <%= f.text_field :email, autofocus: true, class: 'form-control', placeholder: "Enter email", required: true  %>
  </div>
  </br>
  <div class="form-group" style="width: 30%;">
    <%= f.label :name, '*Phone Number*' %>
    <%= f.text_field :phone_number, autofocus: true, class: 'form-control', placeholder: "Phone Number", required: true %>
  </div>
  </br>
  <div class="form-group" style="width: 30%;">
    <%= f.label :subject, '*Subject*' %>
    <%= f.select :subject, Contact.subjects_i18n.keys.map{|k| [I18n.t("enums.contact.subject.#{k}"), k]}, required: true %>

  </div>
  </br>
  <div class="form-group" style="width: 30%;">
    <%= f.label :message, '*Message*' %>
    <%= f.text_area :message, size: '10x10', class: 'form-control', placeholder: "Message", required: true %>
  </div>
  </br>
  <div>
    <%= f.submit '入力内容確認', class: "btn btn-primary" %>
  </div>
  </br>
<% end %>

app/views/homes/company_profile.html.erb
<br>
<h2>会社概要</h2>
<nav aria-label="パンくずリスト" class="small">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'トップページ', homes_path %></li>
    <li class="breadcrumb-item active" aria-current="page">会社概要</li>
  </ol>
</nav>
<hr />
<table class="table">
  <tbody>
    <tr>
      <th scope="row">会社名</th>
      <td>宗教法人 オウム浅沼</td>
    </tr>
    <tr>
      <th scope="row">資本金</th>
      <td>10.000円</td>
    </tr>
    <tr>
      <th scope="row">設立</th>
      <td>2023年8月</td>
    </tr>
    <tr>
      <th scope="row">所在地</th>
      <td colspan="2">江戸川区中葛西</td>
    </tr>
  </tbody>
</table>

app/views/homes/index.html.erb
<body>
  <header>
    <div class="back">
      <div class="top_title">
        <h1>安心、安い、安全</h1>
        <p>トータルWEB戦略</p>
        <p><img src="assets/top2.png"></p>
      </div>
    </div>
  </header>
  <main>
    <div class="reason">
      <div class="reason_title">
        <h1><span>浅沼簡単HP作成館の浅沼館が</span>選ばれる理由</h1>
        <p>1.制作後の安心できるサポート対応</p>
        <p>2.見積もり無料</p>
        <p>3.お客様が求めてる物を確実に制作</p>
        <p>4.専門知識がなくともその道のプロが分かりやすく説明</p>
      </div>
      <div class="content">
        <h1>作品事例</h1>
      </div>
      <div class="reason_explanation_1">
        <p><a href="https://devenues.com/" target="_blank" rel="noopener"><img src="assets/devenue.png"></a></p>
        <div class="box-017">
          <div><h4>WEBサイト・ホームページ制作</h4></div>
          <p>
            浅沼館では。ホームページを「名刺代わりや信用のために持ちたい」、「集客・採用をしていきくために必要」などお客様の様々なご要望に対して
            担当者がお客様の店舗・オフィスへ伺う訪問提案、もしくはオンラインでの提案をいたします。
            そのため、電話のみでホームページを制作・作成する業者とは違い、お客様のイメージしているホームぺージに近いホームぺージを制作することが可能です。
          </p>
        </div>
      </div>
      <div class="reason_explanation_2">
        <div class="box-017">
          <div><h4>予約機能・お問合せ機能・LINE予約機能</h4></div>
          <p>
            こちらは脱毛専用の予約システムとなっており施術したい箇所を
            クリックするとその箇所の予約ができます。
            予約するお客さまの施術したい箇所のみ選択できることで
            予約がスムーズに進みます。
          </p>
        </div>
        <p><a href="https://mens.knux.jp/"><img src="assets/asanuma.png" target="_blank" rel="noopener"></a></p>
      </div>
      <div class="reason_explanation_3">
        <p><a href="https://soichi-furniture.com/"><img src="assets/souithi.png" target="_blank" rel="noopener"></a></p>
        <div class="box-017">
          <div><h4>EC・ERP・勤怠管理・システム運用</h4></div>
          <p>
            家具屋さんのECサイトになります。運営様が作成した家具などの商品を載せることができ
            その家具を販売することも可能です。
          </p>
        </div>
      </div>
    </div>
    <div class="back_question">
      <div class="question">
        <h1>よくある質問 <span>(Q&A)</span></h1>
        <details class="qa-006">
          <summary>既にホームページを持っているのですが、リニューアルは可能ですか？</summary>
          <p>
            もちろん可能です。Devenueがご依頼を受ける案件の半分はリニューアルです。
            Devenueではこれまで「古くなった」「更新ができない」「より効果が出るホームページが欲しい」といったお客様の悩みに応えてきました。
            リニューアル後まで専門スタッフのサポートがついておりますので安心しておまかせいただけます。ぜひお気軽にご相談ください。
            お客様の現状とご要望を検討した上で、最適な提案をさせていただきます。
          </p>
        </details>
        <details class="qa-006">
          <summary>ホームページについて詳しくないのですが、相談できますか？</summary>
          <p>
            Devenueでは、一般的なウェブ業者のように専門用語は使いませんのでご安心ください。どなたにもわかりやすい資料をご用意し、一つ一つご説明します。
            弊社では、技術的なお話よりも、経営者様がどのような課題をお持ちであるかをしっかりお聞きし、課題解決策をご提案しています。
            ホームページを活用することでどんなメリットがあるか、まずは簡単に分かる「無料診断」を行わせていただいています。
          </p>
        </details>
        <details class="qa-006">
          <summary>どんな支払い方法がありますか？</summary>
          <p>
            月額払い、分割払いなど、いくつかの支払いプランをご用意しています。
            初期投資を抑えたい企業様の多くは、初期費用０円の分割払いをご利用いただいています。
            お客様に一番合った料金プランをお選びください。
          </p>
        </details>
        <details class="qa-006">
          <summary>スマートフォン対応もしてもらえますか？</summary>
          <p>
            Googleが推奨するレベルでのスマートフォン対応を標準仕様にしております。
            Devenueでは特に、スマートフォン閲覧者の割合のほうが圧倒的に多いお客様もいらっしゃいます。
          </p>
        </details>
        <details class="qa-006">
          <summary>見積もりをお願いしたいのですが有料ですか？</summary>
          <p>
            お見積りは無料です。お客様から正式にご注文をいただくまでは、料金を頂くことはございませんのでご安心ください。
          </p>
        </details>
        <details class="qa-006">
          <summary>補助金制度はありますか？</summary>
          <p>
            はい、補助⾦のご活⽤‧申請⽅法などご相談ください。補助⾦によるWeb活⽤‧ホームページ制作を承ります。
          </p>
        </details>
      </div>
    </div>
    <div class="bottom">
      <div class="link">
        <div class="box-001">
          <a href="https://devenues.com/about" target="_blank" rel="noopener">
            <svg class="window-bar" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="ウインドウのボタン">
              <circle cx="5" cy="4" r="2" fill="#f48384"/>
              <circle cx="15" cy="4" r="2" fill="#fbd172"/>
              <circle cx="25" cy="4" r="2" fill="#82c880"/>
            </svg>
            <h1>company</h1>
            <p>会社概要</p>
          </a>
        </div>
        <div class="box-001">
          <a href="https://devenues.com/contact" target="_blank" rel="noopener">
            <svg class="window-bar" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="ウインドウのボタン">
              <circle cx="5" cy="4" r="2" fill="#f48384"/>
              <circle cx="15" cy="4" r="2" fill="#fbd172"/>
              <circle cx="25" cy="4" r="2" fill="#82c880"/>
            </svg>
            <h1>contact</h1>
            <p>お問合せ</p>
          </a>
        </div>
        <div class="box-001">
        <a href="" target="_blank" rel="noopener">
            <svg class="window-bar" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="ウインドウのボタン">
              <circle cx="5" cy="4" r="2" fill="#f48384"/>
              <circle cx="15" cy="4" r="2" fill="#fbd172"/>
              <circle cx="25" cy="4" r="2" fill="#82c880"/>
            </svg>
            <h1>support</h1>
            <p>サポート</p>
          </a>
        </div>
      </div>
    </div>
    <div class="footer">
      <p>© 2023 <a href = "https://devenues.com/">Devenue Inc.</a>All Rights Reserved.</p>
    </div>
  </main>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>EasilyPetite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Rakus</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:700 rel="stylesheet">
    <%= stylesheet_link_tag params[:controller] %>
  </head>
  <body>
    
    
    <%= yield %>

    
  </body>
</html>